FROM mcr.microsoft.com/dotnet/core/runtime:3.1
WORKDIR /app
COPY Kosta.DevOpsChallenge.FileProcessor/bin/Release/netcoreapp3.1/publish .
ENTRYPOINT [ "dotnet", "Kosta.DevOpsChallenge.FileProcessor.dll" ]
