name: Build and Package File Processor

on:
  push:
    branches:
    - master
    paths:
    - 'src/file-processor/**'
    - '.github/workflows/file-processor.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: './src/file-processor'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish
      run: dotnet publish --configuration Release --no-build
      working-directory: ${{env.working-directory}}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: file-processor-artifacts
        path: |
          ${{env.working-directory}}/Kosta.DevOpsChallenge.FileProcessor/bin/Release/netcoreapp3.1/publish
    - name: Build and push docker container to Azure Container Registry
      id: acr
      uses: ams0/acr-task-github-action@v2
      with:
        service_principal: ${{ secrets.service_principal }}
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant: ${{ secrets.tenant }}
        registry: ${{ secrets.registry }}
        repository: ${{ secrets.repository }}
        image: file-processor
        dockerfile: ${{env.working-directory}}/Dockerfile
