name: Build and Package File Processor

on:
  push:
    branches:
    - master
    paths:
    - 'src/file-processor/**'
    - '.github/workflows/file-processor.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: 'src/file-processor'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
